txd = engineLoadTXD ( "assets/247/loja.txd" )
engineImportTXD ( txd, 1858 )
col = engineLoadCOL ( "assets/247/loja.col" )
engineReplaceCOL ( col, 1858 )
dff = engineLoadDFF ( "assets/247/loja.dff" )
engineReplaceModel ( dff, 1858 )

txd = engineLoadTXD ( "assets/247/ext.txd" )
engineImportTXD ( txd, 1853 )
dff = engineLoadDFF ( "assets/247/ext.dff" )
engineReplaceModel ( dff, 1853 )
col = engineLoadCOL ( "assets/247/ext.col" )
engineReplaceCOL ( col, 1853 )

txd = engineLoadTXD ( "assets/247/post.txd" )
engineImportTXD ( txd, 1854 )
dff = engineLoadDFF ( "assets/247/post.dff" )
engineReplaceModel ( dff, 1854 )
col = engineLoadCOL ( "assets/247/post.col" )
engineReplaceCOL ( col, 1854 )

txd = engineLoadTXD ( "assets/247/counter.txd" )
engineImportTXD ( txd, 1859 )
dff = engineLoadDFF ( "assets/247/counter.dff" )
engineReplaceModel ( dff, 1859 )
col = engineLoadCOL ( "assets/247/counter.col" )
engineReplaceCOL ( col, 1859 )

txd = engineLoadTXD ( "assets/247/fridge.txd" )
engineImportTXD ( txd, 1857 )
dff = engineLoadDFF ( "assets/247/fridge.dff" )
engineReplaceModel ( dff, 1857 )
col = engineLoadCOL ( "assets/247/fridge.col" )
engineReplaceCOL ( col, 1857 )

txd = engineLoadTXD ( "assets/247/door.txd" )
engineImportTXD ( txd, 1502 )
dff = engineLoadDFF ( "assets/247/door.dff" )
engineReplaceModel ( dff, 1502 )
col = engineLoadCOL ( "assets/247/door.col" )
engineReplaceCOL ( col, 1502 )

