addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD ( "1.txd" )
engineImportTXD ( txd, 5418 )
col = engineLoadCOL ( "1.col" )
engineReplaceCOL ( col, 5418 )
dff = engineLoadDFF ( "1.dff", 0 )
engineReplaceModel ( dff, 5418 )
engineSetModelLODDistance(5418, 500)
end)